config/routes.rb
Ratebeer::Application.routes.draw do

  resources :beer_clubs

  root :to => 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, :only => [:index, :new, :create, :destroy]
  resources :beers
  resources :users
  get '/signup', to: 'users#new'
  resources :sessions, :only => [:new, :create, :destroy]
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  match "/join/:id", :to => "beer_clubs#join", :as => "join"

  resources :places, :only => [:index, :show]

  post "places" => "places#search"

  resources :breweries

  get 'beerlist' => 'beers#list'

  resources :breweries do
    post 'toggle_activity', :on => :member
  end

  match "memberships/:id/confirm" => "beer_clubs#confirm_membership", :as => "confirm_membership"

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  attr_accessible :city, :founded, :name

  validates :name, :presence => :true



  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships


  def members
    memberships.where(:confirmed => true)
  end

  def pending
   return memberships.where(:confirmed => [false, nil])
  end

end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  # GET /beer_clubs
  # GET /beer_clubs.json

  before_filter :ensure_that_signed_in, :except => [:index, :show]

  def index
    @beer_clubs = BeerClub.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beer_clubs }
    end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def join
      @beer_club = BeerClub.find(params[:id])
      if Membership.where(:beer_club_id => @beer_club.id, :user_id => current_user.id).exists?
        respond_to do |format|
                format.html { redirect_to :back, notice: "You are already a member of this club!" }
          end
      else
      @membership = Membership.create
      @membership.beer_club_id = @beer_club.id
      @membership.user_id = current_user.id
      if @beer_club.memberships.count < 1
      @membership.confirmed = true
      else
        @membership.confirmed = false
        end
      respond_to do |format|
    if @membership.save
      format.html { redirect_to :back, notice: "You joined #{@beer_club.name}" }
    else
      format.html { redirect_to :back, notice: "Something went awry! D:" }
    end
        end
  end
  end

  def confirm_membership
    user = User.find(params[:id])
    membership = Membership.where(:user_id => params[:id], :beer_club_id => self)
    membership.confirmed = true
    membership.save
    redirect_to :back
  end

  def show

    @beer_club = BeerClub.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer_club }
    end
  end

  # GET /beer_clubs/new
  # GET /beer_clubs/new.json
  def new
    @beer_club = BeerClub.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beer_club }
    end
  end

  # GET /beer_clubs/1/edit
  def edit
    @beer_club = BeerClub.find(params[:id])
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(params[:beer_club])

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to join_path(@beer_club), notice: 'Beer club was successfully created.' }

      else
        format.html { render action: "new" }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beer_clubs/1
  # PUT /beer_clubs/1.json
  def update
    @beer_club = BeerClub.find(params[:id])

    respond_to do |format|
      if @beer_club.update_attributes(params[:beer_club])
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club = BeerClub.find(params[:id])
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br />
    <%= f.text_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer_club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club %> |
<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/index.html.erb
<h1>Listing Beer Clubs</h1>

<p id="notice"><%= notice %></p>

<table class="table table-hover">
  <thead>
    <th>Name</th>
    <th>Founded</th>
    <th>City</th>
    <th></th>
    <th></th>

  </thead>
                                      <tbody>
<% @beer_clubs.each do |beer_club| %>
  <tr>
    <td><%= link_to beer_club.name, beer_club %></td>
    <td><%= beer_club.founded %></td>
    <td><%= beer_club.city %></td>
    <td><%= link_to 'Show', beer_club %></td>
    <td><%= button_to 'Join', join_path(beer_club)%>
  </tr>
<% end %>
                                      </tbody>
</table>

<br />

<%= link_to 'New Beer club', new_beer_club_path %>

app/views/beer_clubs/new.html.erb
<h1>New beer_club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path %>

app/views/beer_clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @beer_club.name %>
</p>

<p>
  <b>Founded:</b>
  <%= @beer_club.founded %>
</p>

<p>
  <b>City:</b>
  <%= @beer_club.city %>
</p>

<p><b> Honourable members: </b></p>
<ul>
  <% @beer_club.members do |membership| %>
      <li><%= link_to membership.user.username, user %></li>
  <% end %>
</ul>
<% if current_user && current_user.member_of(@beer_club) && @beer_club.pending.size > 0 %>
    <b>Pending approval: </b>
    <% @beer_club.pending.each do |unconfirmed_membership| %>
        <table class="table table-hover">
          <thead>
          <tr>
            <td><%= unconfirmed_membership.user.username %></td>
            <td><%= link_to 'Confirm', confirm_membership_path(unconfirmed_membership), :class => "btn" %></td>
          </tr>
          </thead>
        </table>
    <% end %>
<% end %>


<p>Want to join? <%= link_to "Click here!", join_path(@beer_club) %></p>



<%= edit_and_destroy_buttons(@beer_club) %>