config/routes.rb
Ratebeer::Application.routes.draw do

  resources :beer_clubs

  root :to => 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, :only => [:index, :new, :create, :destroy]
  resources :beers
  resources :users
  get '/signup', to: 'users#new'
  resources :sessions, :only => [:new, :create, :destroy]
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  match "/join/:id", :to => "beer_clubs#join", :as => "join"

  resources :places, :only => [:index, :show]

  post "places" => "places#search"

  resources :breweries

  get 'beerlist' => 'beers#list'

  resources :breweries do
    post 'toggle_activity', :on => :member
  end

  match "memberships/:id/confirm" => "beer_clubs#confirm_membership", :as => "confirm_membership"

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  attr_accessible :name, :year, :active

  scope :active, where(:active => true)
  scope :retired, where(:active => [nil, false])

  include AverageRating
  has_many :beers
  has_many :ratings, :through => :beers

  validates :name, :presence => true
  validates_numericality_of :year, { :greater_than_or_equal_to => 1042,
                                      :only_integer => true }
  validate :not_in_future


  def not_in_future
    if year.presence && year > Time.now.year
      errors.add(:year, "can't be in the future")
    end
    end
=begin

  def average_ratings
    @ratings = self.ratings
    return (self.ratings.inject(0.0) { |result, rating | result + rating.score }) / self.ratings.size
  end
=end

  def self.top(n)

    breweries_with_avg_rating = []
    Brewery.all.each do |b|
      if b.average_rating(b.ratings) > 0
        breweries_with_avg_rating.push(b)
      end
    end

    sorted_by_rating_in_desc_order = breweries_with_avg_rating.sort_by{ |b| -b.average_rating(b.ratings) }.first(n)

  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  # GET /breweries
  # GET /breweries.json

  before_filter :ensure_that_signed_in, :except => [:index, :show]
  before_filter :admin?, :only => [:destroy]


  def index
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @breweries }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, :notice => "brewery activity status changed to #{new_status}"
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brewery }
    end
  end

  # GET /breweries/new
  # GET /breweries/new.json
  def new
    @brewery = Brewery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brewery }
    end
  end

  # GET /breweries/1/edit
  def edit
    @brewery = Brewery.find(params[:id])
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(params[:brewery])

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render json: @brewery, status: :created, location: @brewery }
      else
        format.html { render action: "new" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /breweries/1
  # PUT /breweries/1.json
  def update
    @brewery = Brewery.find(params[:id])

    respond_to do |format|
      if @brewery.update_attributes(params[:brewery])
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  private

  def authenticate
    admin_accounts = {"admin" => "secret", "pekka" => "beer", "arto" => "foobar", "matti" => "ittam"}

    authenticate_or_request_with_http_basic do |username, password|
      admin_accounts[username] == password
    end
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
    <div class="field">
      <%= f.label :active %>
      <%= f.check_box :active %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Year</th>
  </tr>
  </thead>
  <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
      </tr>
  <% end %>
</table>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Breweries</h1>

<h2>Active</h2>

<p> number active of breweries <%= @active_breweries.count %> </p>
<%= render 'list', :breweries => @active_breweries %>

<h2>Retired</h2>

<p> number retired of breweries <%= @retired_breweries.count %> </p>
<%= render 'list', :breweries => @retired_breweries %>

<br/>

<%= link_to('New Brewery', new_brewery_path, :class => "btn btn-primary") if currently_signed_in?(current_user) %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @brewery.name %>
  <% if not @brewery.active  %>
      <span class="label">retired</span>
  <% end %>
</h2>
<p>
  <i>Established year <%= @brewery.year %></i>

</p>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), :method => :post, :class => "btn" %>

<p>
  <b>Rating average</b>
<p>
  <% if @brewery.ratings.empty? %>
      No ratings available.
  <% else %>
      Average of <%= pluralize@brewery.ratings.count, "rating", "ratings" %>  was <%= round @brewery.average_rating(@brewery.ratings) %>
  <% end %>
</p>
</p>

<p>
  <b>Number of products: <%= @brewery.beers.count %></b>
</p>

<p><b> Available products: </b></p>
    <ul>
<% @brewery.beers.each do |beer| %>
      <li><%= link_to beer.name, beer %></li>
          <% end %>
          </ul>


<%= edit_and_destroy_buttons(@brewery) %>
<%= link_to 'Back', breweries_path %> |
<%= link_to 'All Beers', beers_path %>