config/routes.rb
Ratebeer::Application.routes.draw do

  resources :beer_clubs

  root :to => 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, :only => [:index, :new, :create, :destroy]
  resources :beers
  resources :users
  get '/signup', to: 'users#new'
  resources :sessions, :only => [:new, :create, :destroy]
  get '/signin', to: 'sessions#new'
  delete '/signout', to: 'sessions#destroy'
  match "/join/:id", :to => "beer_clubs#join", :as => "join"

  resources :places, :only => [:index, :show]

  post "places" => "places#search"

  resources :breweries

  get 'beerlist' => 'beers#list'

  resources :breweries do
    post 'toggle_activity', :on => :member
  end

  match "memberships/:id/confirm" => "beer_clubs#confirm_membership", :as => "confirm_membership"

end

app/views/layouts/application.html.erb
<%= stylesheet_link_tag "bootstrap", media: "all" %>
<%= stylesheet_link_tag "bootstrap-responsive", media: "all" %>
<%= javascript_include_tag "jquery" %>
<%= javascript_include_tag "bootstrap"%>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Ratebeer</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to 'breweries', breweries_path %></li>
          <li><%= link_to 'beers', beers_path %></li>
          <li><%= link_to 'ratings', ratings_path %></li>
          <li><%= link_to 'users', users_path %></li>
          <li><%= link_to 'clubs', beer_clubs_path %></li>
          <li><%= link_to 'places', places_path %></li>
          <% if current_user.nil? %>
              <li><%= link_to 'signin', signin_path %></li>
              <li><%= link_to 'signup', signup_path %></li>
          <% else %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 <%= current_user.username %>
                  <b class="caret"></b>
                </a>
              <ul class="dropdown-menu">
              <li><%= link_to current_user.username, current_user %></li>
              <li><%= link_to "rate a beer", new_rating_path %></li>
              <li><%= link_to "join a club", beer_clubs_path %></li>
              <li><%= link_to 'signout', signout_path, :method => :delete%></li>
              </ul>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span9">
      <%= yield %>
    </div>
    <div class="span3">
      <img src="http://www.cs.helsinki.fi/u/mluukkai/olut.jpg" width="100">
    </div>
  </div>
</div>